language: node_js
node_js:
  - "10"

before_script:
  - npm run setup
  - npm run build

script:
  - npm run lint

after_success:
  - npm run typedoc
  - npm pack

before_deploy:
  - npm version patch

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "@enigmatis/polaris-logs-*.tgz"
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: "bikov95@gmail.com"
    api_key: $NPM_TOKEN
    on:
      branch: master