language: node_js
node_js:
  - "10"

before_script:
  - npm run setup
  - npm run build

script:
  - npm run lint

after_success:
  - npm run typedoc
  - npm pack

before_deploy:
  - |
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      rvm --default use system;
      wget https://github.com/spf13/hugo/releases/download/v0.25.1/hugo_0.25.1_Linux-64bit.deb;
      sudo dpkg -i hugo_0.25.1_Linux-64bit.deb;
      rm *.deb;
      sudo apt-get install -y ruby ruby-dev;
      sudo gem install --no-ri --no-rdoc fpm;
      make documentation;
      GOOS=linux GOARCH=amd64 make package package-deb;
      GOOS=linux GOARCH=386 make package package-deb;
      GOOS=linux GOARCH=arm make package package-deb;
      GOOS=darwin GOARCH=amd64 make package;
      GOOS=windows BINEXT=.exe GOARCH=386 make package;
      GOOS=windows BINEXT=.exe GOARCH=amd64 make package;
    fi

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
        branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "@enigmatis/polaris-logs-*.tgz"
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: "bikov95@gmail.com"
    api_key: $NPM_TOKEN
    on:
        branch: master
  - provider: npm
      skip_cleanup: true
      email: "bikov95@gmail.com"
      api_key: $NPM_TOKEN
      tag: next
      on:
          branch: develop
